agent:
  model:
    api_base: "http://127.0.0.1:8000/v1"
    api_key: "dummy-key-ok"
    max_input_tokens: 131072
    max_output_tokens: 131072
    per_instance_cost_limit: 0
    name: openai/openai/gpt-oss-120b

env:
  deployment:
    type: docker
    container_runtime: podman
    pull: missing
    docker_args:
      - --ipc=host
      - --runtime=crun

  repo:
    path: /repo
