agent:
  model:
    api_base: "http://127.0.0.1:8008/v1"
    api_key: "dummy-key-ok"
    max_input_tokens: 24576
    max_output_tokens: 16384
    per_instance_cost_limit: 0
    name: openai/google/gemma-4-31B-it

env:
  deployment:
    type: docker
    container_runtime: podman
    pull: missing
    docker_args:
      - --ipc=host
      - --runtime=crun

  repo:
    path: /repo
